[general]
import = [
#"~/.config/alacritty/colors/nord-colors.toml",
#"~/.config/alacritty/colors/moonlight-colors.toml",
"~/.config/alacritty/colors/contrast-colors.toml",
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
       
[window]
padding = { x = 20, y = 20 }

[scrolling]
history = 5000

[cursor]
style = { blinking = "Always" }
thickness = 0.2

[terminal]
shell = "fish"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", mods = "Control", action = "Copy" },
    { mouse = "Right", action = "Paste" },
]

[font]
normal = { family = "GeistMono NF" }
bold = { family = "GeistMono NF" }
italic = { family = "GeistMono NF" }
bold_italic = { family = "GeistMono NF" }
size = 9.5

