[colors]
# Paleta inspirado en Moonlight II

[colors.primary]
background = "0x1e2030"  
foreground = "0xc8d3f5"  

[colors.normal]
black   = "0x1b1d2b"
red     = "0xff757f"  
green   = "0xc3e88d"  
yellow  = "0xffc777"  
blue    = "0x82aaff"  
magenta = "0xc099ff"  
cyan    = "0x86e1fc"  
white   = "0x828bb8"

[colors.bright]
black   = "0x444a73"
red     = "0xff757f"
green   = "0xc3e88d"
yellow  = "0xffc777"
blue    = "0x82aaff"
magenta = "0xc099ff"
cyan    = "0x86e1fc"
white   = "0xc8d3f5"
